### ISSUE TITLE
Not triggering Laravel model observer updated & deleted events

### ISSUE THREAD

**Issue by MerlinGeorg** [MerlinGeorg/Projects#1]
**Observer**
    class FileLogObserver
    {
    function updated(FileLogs $fileLogs)
    {
        $fileChangeLogs = FileChangeLogs::firstWhere('fileId', $fileLogs->filedId);

        if ( !empty($fileChangeLogs)) {
            $fileChangeLogs->save([
                'logDetails' => '1 file updated',
            ]);
        }
    }
  }

**Controller**
    class FileLogController extends Controller
   {
    public function update(Request $request,$id){  
            
            $validator = Validator::make(
                $request->all(),
                [
                    
                    'orderId'    => 'required|integer',
                    'fileId'    => 'required|integer',
                    'status'    => 'required|string'
                ]
            );
    
            if ($validator->fails()) {
                return response()->json($validator->errors(), 400);
            }
    
            $data = FileLogs::find($id); 
            if($data){
               $data->orderId=$request->orderId;
               $data->fileId=$request->fileId;
               $data->status=$request->status;
               $data->update();
            
                return response()->json(['status'=>'success','StatusCode'=> 200,'message'=>'Successfully Updated','data'=>$data]);
            }
            else{
                return response()->json(['status'=>'Failed','message'=>'Update Failed'],400);
            }
        }
}

The created & retrieved methods are being properly triggered. However, the updated & deleted methods not triggered. Gone through many links & read that a reason can be becoz the update is not directly on the model. so, i tried like below in my controller. But that too doesn't trigger the `updated` event.  Any help is much appreciated.

       $data=FileLogs::find($id)->update(['orderId'=>$request->orderId,'fileId'=>$request->fileId,'status'=>$request->status]);

**Comment by hmreumann** [comment]
Hallo, how are you? Could you solve it? Are you sure that the orderId, fileId, status are fillable properties in the model and that have corresponding type according to the DB? Hope you solve it.
